name: Deploy Docker
version: '3.4'

on:
  push:
    branches:
      - 'issue1'
  pull_request:
    branches:
      - 'issue1'
  create:
    branches:
      - "*"

jobs:
  services:
    pmdutils:
      image: pmdutils
      build:
        context: ../
        dockerfile: ./deploydocker/Dockerfile
  # steps:
  # - name: Run pyright
  #   run: poetry run pyright . --lib
  # - name: Run unittests
  #   run: poetry run pytest --junitxml=pytest_results_pmd.xml
  # - name: Run behaviour tests
  #   run: poetry run behave tests/features --tags=-skip -f json.cucumber -o tests/behaviour/test-results.json
