name: build push dev image

on:
  push:
    branches:
      - 'issue1'

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build pmdutils:dev
        uses: docker/build-push-action@v2
        id: docker_build_dev
        with:
          context: .
          file: deploydocker/Dockerfile
          push: true
          build-args: dev=true
          tags: |
            gsscogs/pmdutils:dev
      - name: Run pyright
        uses: docker/build-push-action@v2
        id: docker_build_dev
        with:
          context: .
          file: deploydocker/Dockerfile
        run: python3 poetry shell && pyright . --lib
      - name: Run unittests 
        uses: docker/build-push-action@v2
        id: docker_build_dev
        with:
          context: .
          file: deploydocker/Dockerfile
        run: python3 poetry run pytest --junitxml=pytest_results_pmd.xml
      - name: Run behaviour tests
        uses: docker/build-push-action@v2
        id: docker_build_dev
        with:
          context: .
          file: deploydocker/Dockerfile
        run: python3 poetry run behave tests/features --tags=-skip -f json.cucumber -o tests/behaviour/test-results.json
      - name: Develop Image digest
        run: echo ${{ steps.docker_build_dev.outputs.digest }}