name: build push dev image

on:
  push:
    branches:
      - 'issue1'

jobs:
  testing:
      runs-on: ubuntu-latest
      container:
        image: gsscogs/pythonversiontesting
      strategy:
        matrix:
          python-version: ["3.10"]

      steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        run: |
          poetry install
          export python_dir=$(poetry run python -c "import site; print(site.getsitepackages()[0])") && patch -Nf -d "$python_dir/behave/formatter" -p1 < /cucumber-format.patch

      - name: Run pyright
        run: poetry run pyright . --lib

      - name: Run unittests
        if: always()
        run: poetry run pytest --junitxml=pytest_results_pmd.xml

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "pytest_results_pmd.xml"

      - name: Run behaviour tests
        if: always()
        run: poetry run behave tests/features --tags=-skip -f json.cucumber -o tests/behaviour/test-results.json

      - name: convert json to xml
        if: always()
        uses: fabasoad/yaml-json-xml-converter-action@main
        id: json2xml
        with:
          path: 'tests/behaviour/test-results.json'
          from: 'json'
          to: 'xml'

      - name: Print json2xml result
        if: always()
        run: echo "${{ steps.json2xml.outputs.data }}"

      - name: Publish Behave Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          check_name: "Behave Test Results"
          files: '*/**/tests/behaviour/test-results.xml'

  dev:
    if: github.event_name == 'create'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build pmdutils:dev
        uses: docker/build-push-action@v2
        id: docker_build_dev
        with:
          context: .
          file: deploydocker/Dockerfile
          push: true
          build-args: dev=true
          tags: |
            gsscogs/pmdutils:dev
      - name: Develop Image digest
        run: echo ${{ steps.docker_build_dev.outputs.digest }}